import Head from 'next/head';
import { Grid } from '@chakra-ui/react';

export default function Databases() {
  return (
    <>
      <Head>
        <title>HETIC Cloud - Groupe 3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid p={4} alignContent={'center'}>
        <h1>No database found!</h1>
      </Grid>
    </>
  );
}
